name: Update the Jellyfin SDK

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

concurrency:
  group: unstable-sdk-pr
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'jellyfin/jellyfin-web' }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: master
          token: ${{ secrets.JF_BOT_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20
          check-latest: true
          cache: npm

      - name: Install latest unstable SDK
        run: |
          npm i --save @jellyfin/sdk@unstable
          git checkout package.json

      - name: Open a pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.JF_BOT_TOKEN }}
          commit-message: Update @jellyfin/sdk
          committer: jellyfin-bot <team@jellyfin.org>
          author: jellyfin-bot <team@jellyfin.org>
          branch: update-jf-sdk
          delete-branch: true
          title: Update @jellyfin/sdk
          body: |
            **Changes**
            Updates to the latest unstable @jellyfin/sdk build
          labels: |
            dependencies
            npm
